### ISSUE TITLE
Change absolute links to relative links

### ISSUE THREAD

**Issue by ayan-b** [ayan-b/blog#25]

**Comment by monsij** [comment]
Can i work?

**Comment by ayan-b** [comment]
Sure!

**Comment by monsij** [comment]
Where in the changes are to be made, as I could not find any absolute links @ayan-b

**Comment by ayan-b** [comment]
There is also a netlify site: https://material-design-jekyll.netlify.com/ and it is not rendered properly. I thought this is due to this problem. Let me check if that is the case.

**Comment by ayan-b** [comment]
Got it. It is due to base url problem. Thanks for pointing out!
